#:schema node_modules/wrangler/config-schema.json
name = "citation-generator"
# main = "src/index.ts"
compatibility_date = "2024-04-18"
compatibility_flags = ["nodejs_compat"]

[env]
API_KEY = "AIzaSyDCFqstQDhj-FshO68XMi-lrJTbGNLL5_Q"