// AUTO-GENERATED by scripts/embed-csl.mjs — do not edit by hand.
import ama_11_b64 from './ama-11';
import apa_7_b64 from './apa-7';
import chicago_17_b64 from './chicago-17';
import harvard_b64 from './harvard';
import ieee_b64 from './ieee';
import mla_9_b64 from './mla-9';
import vancouver_b64 from './vancouver';

const ENCODED: Record<string, string> = {
    'ama-11': ama_11_b64,
    'apa-7': apa_7_b64,
    'chicago-17': chicago_17_b64,
    'harvard': harvard_b64,
    'ieee': ieee_b64,
    'mla-9': mla_9_b64,
    'vancouver': vancouver_b64,
};

/** Decode an embedded base64-encoded asset to a UTF-8 string. */
export function decode(name: string): string {
    const b64 = ENCODED[name];
    if (!b64) throw new Error(`Embedded asset not found: ${name}`);
    // atob is available in the Cloudflare Workers runtime.
    const binary = atob(b64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return new TextDecoder('utf-8').decode(bytes);
}

export const NAMES = Object.keys(ENCODED);
