import { capitalizeFirstLetter } from "../utils";

const knownPublishers = {
    "wikipedia": "Wikimedia Foundation",
    "youtube": "Google",
    "facebook": "Facebook",
    "twitter": "Twitter",
    "instagram": "Facebook",
    "linkedin": "LinkedIn",
    "pinterest": "Pinterest",
    "tumblr": "Tumblr",
    "reddit": "Reddit",
    "snapchat": "Snap Inc.",
    "whatsapp": "Facebook",
    "telegram": "Telegram",
    "tiktok": "ByteDance",
    "vimeo": "IAC",
    "flickr": "SmugMug",
    "medium": "A Medium Corporation",
    "wordpress": "Automattic",
    "blogger": "Google",
    "twitch": "Amazon",
    "github": "GitHub",
    "gitlab": "GitLab",
    "bitbucket": "Atlassian",
    "stackoverflow": "Stack Exchange",
    "quora": "Quora",
    "yelp": "Yelp",
    "tripadvisor": "TripAdvisor",
    "ycombinator": "Y Combinator",
    "producthunt": "Product Hunt",
    "indiegogo": "Indiegogo",
    "kickstarter": "Kickstarter",
    "patreon": "Patreon",
    "gofundme": "GoFundMe",
    "changeorg": "Change.org",
    "eventbrite": "Eventbrite",
    "meetup": "Meetup",
    "slack": "Salesforce",
    "discord": "Discord",
    "zoom": "Zoom Video Communications",
    "skype": "Microsoft",
    "messenger": "Facebook",
    "signal": "Signal Foundation",
    "line": "Naver",
    "wechat": "Tencent",
    "qq": "Tencent",
    "kik": "MediaLab",
    "viber": "Rakuten",
    "cnn": "CNN",
    "bbc": "BBC",
    "nytimes": "The New York Times",
    "washingtonpost": "The Washington Post",
    "foxnews": "Fox News",
    "nbcnews": "NBC News",
    "cbsnews": "CBS News",
    "abcnews": "ABC News",
    "usatoday": "USA Today",
    "reuters": "Reuters",
    "apnews": "The Associated Press",
    "bloomberg": "Bloomberg L.P.",
    "forbes": "Forbes",
    "fortune": "Fortune",
    "businessinsider": "Axel Springer SE",
    "wsj": "Dow Jones & Company",
    "ft": "The Nikkei",
    "economist": "The Economist Group",
    "time": "Time",
    "newsweek": "Newsweek",
    "guardian": "Guardian Media Group",
    "huffpost": "HuffPost",
    "buzzfeed": "BuzzFeed",
    "vice": "VICE Media",
    "vox": "Vox Media",
    "theguardian": "The Guardian",
    "bridgew": "Bridgewater State University",
    "jstor": "JSTOR",
    "academicjournals": "Academic Journals",
    "doaj": "Directory of Open Access Journals",
    "researchgate": "ResearchGate",
    "pubmed": "National Center for Biotechnology Information",
    "ncbi": "National Center for Biotechnology Information",
    "sciencedirect": "Science Direct",
}

export function getPublisher(url: string) {
    const domain = new URL(url).hostname;
    const domainParts = domain.split('.');
    const domainName = domainParts[domainParts.length - 2];
    return knownPublishers[domainName] || capitalizeFirstLetter(domainName);
}