// AUTO-GENERATED by scripts/embed-csl.mjs — do not edit by hand.
import locales_en_US_b64 from './locales-en-US';

const ENCODED: Record<string, string> = {
    'locales-en-US': locales_en_US_b64,
};

/** Decode an embedded base64-encoded asset to a UTF-8 string. */
export function decode(name: string): string {
    const b64 = ENCODED[name];
    if (!b64) throw new Error(`Embedded asset not found: ${name}`);
    // atob is available in the Cloudflare Workers runtime.
    const binary = atob(b64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return new TextDecoder('utf-8').decode(bytes);
}

export const NAMES = Object.keys(ENCODED);
