#!/usr/bin/env node
/**
 * Embeds CSL and locale XML files as base64-encoded TypeScript modules.
 *
 * Why: Cloudflare Pages Functions are bundled by Wrangler's esbuild, which
 * does NOT recognize Vite's `?raw` suffix and has no loader registered for
 * `.csl` or `.xml` extensions. Importing those files (with or without
 * `?raw`) fails with "No loader is configured for .csl files".
 *
 * Workaround: Read each `.csl` / `.xml` file, base64-encode the contents,
 * and write a sibling `.ts` module exporting the encoded string. Consumers
 * decode at runtime via `atob` (available in the Workers runtime).
 *
 * Run: `node scripts/embed-csl.mjs`
 *
 * Input directories:
 *   - functions/lib/format/styles/*.csl
 *   - functions/lib/format/locales/*.xml
 *
 * Output: a sibling `<name>.ts` file for every input file, plus an
 *   `index.ts` per directory re-exporting decoded UTF-8 strings.
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, basename, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const TARGETS = [
    { dir: join(ROOT, 'functions/lib/format/styles'), exts: ['.csl'] },
    { dir: join(ROOT, 'functions/lib/format/locales'), exts: ['.xml'] },
];

/** Encode a Buffer to base64 string. */
function toBase64(buf) {
    return buf.toString('base64');
}

/** Convert a filename (e.g. "mla-9.csl") to a safe JS identifier (e.g. "mla_9"). */
function safeIdent(name) {
    return name
        .replace(/\.[^.]+$/, '')
        .replace(/[^a-zA-Z0-9_$]/g, '_')
        .replace(/^([0-9])/, '_$1');
}

let totalFiles = 0;
let totalBytes = 0;

for (const target of TARGETS) {
    const entries = readdirSync(target.dir)
        .filter((f) => target.exts.includes(extname(f).toLowerCase()))
        .sort();

    const indexExports = [];

    for (const file of entries) {
        const fullPath = join(target.dir, file);
        const raw = readFileSync(fullPath);
        const b64 = toBase64(raw);
        const ident = safeIdent(file);
        const outPath = join(target.dir, `${basename(file, extname(file))}.ts`);
        const banner = `// AUTO-GENERATED by scripts/embed-csl.mjs — do not edit by hand.\n` +
            `// Source: ${file} (${raw.length} bytes)\n`;
        const body = `const ${ident}_b64 = "${b64}";\nexport default ${ident}_b64;\n`;
        writeFileSync(outPath, banner + body, 'utf8');
        indexExports.push({ ident, file, outBase: basename(file, extname(file)) });
        totalFiles += 1;
        totalBytes += raw.length;
        console.log(`  wrote ${outPath} (source ${raw.length} B, base64 ${b64.length} B)`);
    }

    // Write an index.ts that exposes a `decode(name)` helper and a map of
    // base-name -> decoded UTF-8 string.
    const indexPath = join(target.dir, 'index.ts');
    const importLines = indexExports
        .map((e) => `import ${e.ident}_b64 from './${e.outBase}';`)
        .join('\n');
    const mapEntries = indexExports
        .map((e) => `    '${e.outBase}': ${e.ident}_b64,`)
        .join('\n');
    const indexBody = `// AUTO-GENERATED by scripts/embed-csl.mjs — do not edit by hand.\n` +
        `${importLines}\n\n` +
        `const ENCODED: Record<string, string> = {\n${mapEntries}\n};\n\n` +
        `/** Decode an embedded base64-encoded asset to a UTF-8 string. */\n` +
        `export function decode(name: string): string {\n` +
        `    const b64 = ENCODED[name];\n` +
        `    if (!b64) throw new Error(\`Embedded asset not found: \${name}\`);\n` +
        `    // atob is available in the Cloudflare Workers runtime.\n` +
        `    const binary = atob(b64);\n` +
        `    const bytes = new Uint8Array(binary.length);\n` +
        `    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);\n` +
        `    return new TextDecoder('utf-8').decode(bytes);\n` +
        `}\n\n` +
        `export const NAMES = Object.keys(ENCODED);\n`;
    writeFileSync(indexPath, indexBody, 'utf8');
    console.log(`  wrote ${indexPath} (${indexExports.length} entries)`);
}

console.log(`\nEmbedded ${totalFiles} files (${totalBytes} source bytes total).`);
